name: SSH Connection Test

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: show current path
        run: |
         #show crrnt path
         echo pwd
         pwd
         ls
         mkdir reddy
         ls -a

