name: SSH Connection Test

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    
    steps:
      # - name: Checkout the repository
      #   uses: actions/checkout@v2
        
      - name: show current path
        run: |
         #show crrnt path
         echo down dir 
         pwd
         echo 'list of files'
         ls
         echo 'make new reddy dir'
         mkdir reddy
         echo 'again listing of files'
         ls -a

