name: SSH Connection Test

on:
  push:
    branches:
      - main  # or any branch you want to trigger this workflow for

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Test SSH Connection
        run: |
          echo "Attempting to SSH into Hostinger server..."
          ssh -o StrictHostKeyChecking=no -p 65002 u334800547@82.112.239.136 "echo 'SSH connection successful!'"
        
      - name: Handle SSH Connection Failure
        if: failure()
        run: |
          echo "SSH connection failed! Please check the credentials and server configuration."
